# Generated by Django 4.2.1 on 2023-06-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Finch',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
